# Create two matrices:

In [88]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

## Multiply matrices A and B:

In [89]:
A*B

array([[ 5, 12],
       [21, 32]])

In [90]:
A

array([[1, 2],
       [3, 4]])

## This command only shows the last input (matrix B):

In [91]:
A
B

array([[5, 6],
       [7, 8]])

## Use `print()` command to show both A and B:

In [92]:
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


# Create a C matrix:

In [93]:
C = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [94]:
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Give information on all variables in environment:

In [95]:
whos

Variable   Type       Data/Info
-------------------------------
A          ndarray    2x2: 4 elems, type `int64`, 32 bytes
A1         ndarray    2x2: 4 elems, type `float64`, 32 bytes
B          ndarray    2x2: 4 elems, type `int64`, 32 bytes
C          ndarray    3x3: 9 elems, type `int64`, 72 bytes
G          ndarray    2x3: 6 elems, type `float64`, 48 bytes
I          ndarray    3x4: 12 elems, type `float64`, 96 bytes
I3         ndarray    3x3: 9 elems, type `float64`, 72 bytes
I4         ndarray    4x4: 16 elems, type `float64`, 128 bytes
M          ndarray    2x2: 4 elems, type `int64`, 32 bytes
M1         ndarray    2x2: 4 elems, type `int64`, 32 bytes
M2         ndarray    2x2: 4 elems, type `int64`, 32 bytes
M3         ndarray    2x2: 4 elems, type `int64`, 32 bytes
MM         ndarray    2x2: 4 elems, type `int64`, 32 bytes
S          ndarray    2x2: 4 elems, type `int64`, 32 bytes
Z4         ndarray    4x4: 16 elems, type `int64`, 128 bytes
np         module     <module 'numpy

## To show the data type:

In [96]:
A.dtype

dtype('int64')

# Create G as a double variable:

In [97]:
G = np.array([[1,2,3],[4,5,6]], np.double)

In [98]:
G

array([[1., 2., 3.],
       [4., 5., 6.]])

In [99]:
whos

Variable   Type       Data/Info
-------------------------------
A          ndarray    2x2: 4 elems, type `int64`, 32 bytes
A1         ndarray    2x2: 4 elems, type `float64`, 32 bytes
B          ndarray    2x2: 4 elems, type `int64`, 32 bytes
C          ndarray    3x3: 9 elems, type `int64`, 72 bytes
G          ndarray    2x3: 6 elems, type `float64`, 48 bytes
I          ndarray    3x4: 12 elems, type `float64`, 96 bytes
I3         ndarray    3x3: 9 elems, type `float64`, 72 bytes
I4         ndarray    4x4: 16 elems, type `float64`, 128 bytes
M          ndarray    2x2: 4 elems, type `int64`, 32 bytes
M1         ndarray    2x2: 4 elems, type `int64`, 32 bytes
M2         ndarray    2x2: 4 elems, type `int64`, 32 bytes
M3         ndarray    2x2: 4 elems, type `int64`, 32 bytes
MM         ndarray    2x2: 4 elems, type `int64`, 32 bytes
S          ndarray    2x2: 4 elems, type `int64`, 32 bytes
Z4         ndarray    4x4: 16 elems, type `int64`, 128 bytes
np         module     <module 'numpy

In [100]:
G.dtype

dtype('float64')

# Zeros & Identity Matrices:

In [101]:
Z4 = np.zeros(shape = (4,4), dtype = int)
Z4

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [102]:
I4 = np.identity(4)
I4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [103]:
I3 = np.eye(3,3)
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Accessing rows and columns of a matrix:

Use C[0,0] to access the value in the first row and column

In [104]:
C[0,0]

1

## Extract the first row and all columns:

In [105]:
C[0,:]

array([1, 2, 3])

## Extract the first column and all rows:

In [106]:
C[:,0]

array([1, 4, 7])

## Extract values in first two rows and columns

In [107]:
C[0:2,0:2]

array([[1, 2],
       [4, 5]])

## Extract values in second and third rows and columns (two ways possible)

In [108]:
C[1:3,1:3]
C[1:,1:]

array([[5, 6],
       [8, 9]])

## Slicing (python assumes the last column is -1, the second to last is -2, etc.)

In [109]:
C[-2:,-2:]

array([[5, 6],
       [8, 9]])

In [110]:
C[-2:,-3:-1]

array([[4, 5],
       [7, 8]])

# return to G matrix

## check G matrix (2 rows and 3 columns)

In [111]:
G.shape

(2, 3)

In [112]:
G.shape

(2, 3)

## Show the first row in the G matrix

In [113]:
G[0]

array([1., 2., 3.])

## Show the second row in the G matrix

In [114]:
G[1]

array([4., 5., 6.])

## transpose the matrix using `matrix.T` command

In [115]:
G.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

# return to matrices A and B

## add A and B

In [116]:
S = A + B
print(S)

[[ 6  8]
 [10 12]]


## multiply A by a scalar

In [117]:
MM = 2 * A
print(MM)

[[2 4]
 [6 8]]


## multiply matrices A and B (this is wrong)

In [118]:
M = A * B
print(A)
print(B)
print(M)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]


## multiply matrices A and B (this is correct)

In [119]:
M1 = np.matmul(A,B)
print(M1)

[[19 22]
 [43 50]]


In [120]:
M2 = A.dot(B)
print(M2)

[[19 22]
 [43 50]]


In [121]:
M3 = A@B
print(M3)

[[19 22]
 [43 50]]


## test the inverse of matrix A

In [122]:
A1 = np.linalg.inv(A)
print(A1)

[[-2.   1. ]
 [ 1.5 -0.5]]


## prove that A1 really is the inverse of A

In [123]:
A@A1

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])